import { Document, Page, View, Text, StyleSheet, Font } from '@react-pdf/renderer'
import path from 'path'
import type { DashboardData } from '@/app/assets/DashboardClient'
import { fmt, fmtPct } from '@/lib/formatters'

Font.register({
  family: 'Roboto',
  fonts: [
    { src: path.join(process.cwd(), 'public/fonts/Roboto-Regular.woff'), fontWeight: 'normal' },
    { src: path.join(process.cwd(), 'public/fonts/Roboto-Bold.woff'), fontWeight: 'bold' },
  ],
})

const labels = {
  vi: {
    title: 'Allocate — Báo cáo danh mục',
    generatedOn: 'Ngày tạo',
    netWorthSection: 'Tổng quan tài sản',
    totalInvested: 'Tổng đầu tư',
    currentValue: 'Giá trị hiện tại',
    profitLoss: 'Lãi / Lỗ',
    assetSection: 'Phân bổ tài sản',
    mutualFunds: 'Quỹ đầu tư',
    bankDeposit: 'Tiền gửi ngân hàng',
    gold: 'Vàng',
    stock: 'Cổ phiếu',
    noAssets: 'Chưa có tài sản nào',
    goalsSection: 'Mục tiêu tiết kiệm',
    invested: 'Đã đầu tư',
    target: 'Mục tiêu',
    complete: 'hoàn thành',
    noTarget: 'Không có mục tiêu',
    footer: 'Báo cáo được tạo bởi Allocate',
  },
  en: {
    title: 'Allocate — Portfolio Report',
    generatedOn: 'Generated on',
    netWorthSection: 'Net Worth Overview',
    totalInvested: 'Total Invested',
    currentValue: 'Current Value',
    profitLoss: 'Profit / Loss',
    assetSection: 'Asset Allocation',
    mutualFunds: 'Mutual Funds',
    bankDeposit: 'Bank Deposits',
    gold: 'Gold',
    stock: 'Stocks',
    noAssets: 'No assets yet',
    goalsSection: 'Savings Goals',
    invested: 'Invested',
    target: 'Target',
    complete: 'complete',
    noTarget: 'No target set',
    footer: 'Report generated by Allocate',
  },
} as const

type Locale = keyof typeof labels

const styles = StyleSheet.create({
  page: { fontFamily: 'Roboto', fontWeight: 'normal', fontSize: 10, padding: 40, color: '#1a1a1a' },
  header: { marginBottom: 24 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#6b7280' },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 8, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { color: '#6b7280' },
  value: { fontWeight: 'bold' },
  positive: { color: '#16a34a' },
  negative: { color: '#dc2626' },
  goalCard: { padding: 10, marginBottom: 8, backgroundColor: '#f9fafb', borderRadius: 4 },
  goalName: { fontSize: 11, fontWeight: 'bold', marginBottom: 6 },
  indent: { paddingLeft: 8 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#9ca3af', fontSize: 8 },
})

function ProfitText({ value, formatted }: { value: number; formatted: string }) {
  return <Text style={value >= 0 ? styles.positive : styles.negative}>{formatted}</Text>
}

function LabelRow({ label, value, profitValue }: { label: string; value: string; profitValue?: number }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      {profitValue !== undefined
        ? <ProfitText value={profitValue} formatted={value} />
        : <Text style={styles.value}>{value}</Text>
      }
    </View>
  )
}

export function PortfolioReport({ data, locale = 'vi' }: { data: DashboardData; locale?: string }) {
  const l = labels[(locale as Locale) in labels ? (locale as Locale) : 'vi']
  const { netWorth, goals, byType } = data
  const generatedDate = new Date().toLocaleDateString(locale === 'vi' ? 'vi-VN' : 'en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' })

  const mutualFundsTotal = [
    ...data.goals.flatMap((g) => g.funds),
    ...data.unallocated.funds,
  ].reduce((sum, f) => sum + f.currentValue, 0)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{l.title}</Text>
          <Text style={styles.subtitle}>{l.generatedOn}: {generatedDate}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{l.netWorthSection}</Text>
          <LabelRow label={l.totalInvested} value={fmt(netWorth.totalInvested)} />
          <LabelRow label={l.currentValue} value={fmt(netWorth.currentValue)} />
          <LabelRow
            label={l.profitLoss}
            value={`${netWorth.overallProfitLoss >= 0 ? '+' : ''}${fmt(netWorth.overallProfitLoss)} (${fmtPct(netWorth.overallProfitLossPercentage)})`}
            profitValue={netWorth.overallProfitLoss}
          />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{l.assetSection}</Text>
          {mutualFundsTotal > 0 && <LabelRow label={l.mutualFunds} value={fmt(mutualFundsTotal)} />}
          {byType.bank > 0 && <LabelRow label={l.bankDeposit} value={fmt(byType.bank)} />}
          {byType.gold > 0 && <LabelRow label={l.gold} value={fmt(byType.gold)} />}
          {byType.stock > 0 && <LabelRow label={l.stock} value={fmt(byType.stock)} />}
          {mutualFundsTotal === 0 && byType.bank === 0 && byType.gold === 0 && byType.stock === 0 && (
            <Text style={styles.label}>{l.noAssets}</Text>
          )}
        </View>

        {goals.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{l.goalsSection}</Text>
            {goals.map((goal) => (
              <View key={goal.goalId} style={styles.goalCard}>
                <Text style={styles.goalName}>{goal.goalName}</Text>
                <View style={styles.indent}>
                  <LabelRow label={l.invested} value={fmt(goal.totalInvested)} />
                  <LabelRow label={l.currentValue} value={fmt(goal.currentValue)} />
                  <LabelRow
                    label={l.profitLoss}
                    value={`${goal.profitLoss >= 0 ? '+' : ''}${fmt(goal.profitLoss)} (${fmtPct(goal.profitLossPercentage)})`}
                    profitValue={goal.profitLoss}
                  />
                  {goal.targetAmount != null && goal.progressPercentage != null ? (
                    <LabelRow label={l.target} value={`${fmt(goal.targetAmount)} — ${goal.progressPercentage.toFixed(1)}% ${l.complete}`} />
                  ) : (
                    <LabelRow label={l.target} value={l.noTarget} />
                  )}
                </View>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footer}>{l.footer} · {generatedDate}</Text>
      </Page>
    </Document>
  )
}
