import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, within } from '@testing-library/react'
import { NextIntlClientProvider, createTranslator } from 'next-intl'
import enMessages from '../../messages/en.json'
import viMessages from '../../messages/vi.json'

// The landing page's static markup — the wordmark, the nav links, the hero copy,
// the six feature cards, the three numbered steps, the CTAs and where each link
// points — used to be pinned by ~20 separate Playwright tests, one browser page
// load each, in e2e/landing.spec.ts (#597). None of it needs a browser: the page
// is a server component that renders the same tree from the same messages here.
//
// What stayed in the E2E spec is what only a real browser can see: that the tour
// screenshot file actually decodes (the PNGs are generated by a script and are
// imported by no module, so a rename yields a broken image every unit test
// happily passes through), and that switching locale round-trips through the
// cookie and a server re-render.

const getUser = vi.fn()
const redirect = vi.fn()

vi.mock('@/lib/supabase-server', () => ({
  createSupabaseServerClient: async () => ({ auth: { getUser } }),
}))

vi.mock('next/navigation', () => ({
  redirect: (...args: unknown[]) => redirect(...args),
  useRouter: () => ({ refresh: vi.fn(), push: vi.fn() }),
  usePathname: () => '/',
}))

let pageLocale: 'en' | 'vi' = 'en'

vi.mock('next-intl/server', () => ({
  getTranslations: async (namespace: 'landing') =>
    createTranslator({
      locale: pageLocale,
      messages: pageLocale === 'vi' ? viMessages : enMessages,
      namespace,
    }),
}))

// ScrollRevealInit observes .reveal elements on mount; jsdom has no observer.
class NoopObserver {
  observe() {}
  disconnect() {}
  unobserve() {}
}

beforeEach(() => {
  pageLocale = 'en'
  getUser.mockResolvedValue({ data: { user: null } })
  redirect.mockReset()
  vi.stubGlobal('IntersectionObserver', NoopObserver)
})

afterEach(() => {
  vi.unstubAllGlobals()
})

async function renderLanding(locale: 'en' | 'vi' = 'en') {
  pageLocale = locale
  const { default: HomePage } = await import('../page')
  const tree = await HomePage()
  return render(
    <NextIntlClientProvider
      locale={locale}
      messages={locale === 'vi' ? viMessages : enMessages}
      timeZone="Asia/Ho_Chi_Minh"
    >
      {tree}
    </NextIntlClientProvider>,
  )
}

describe('landing page — who it is served to', () => {
  it('sends a signed-in visitor straight to the dashboard', async () => {
    getUser.mockResolvedValue({ data: { user: { id: 'u1' } } })
    // redirect() is mocked, so the component keeps rendering past the call —
    // the assertion is that the redirect was requested at all.
    await renderLanding()
    expect(redirect).toHaveBeenCalledWith('/dashboard')
  })

  it('renders the marketing page for a signed-out visitor', async () => {
    await renderLanding()
    expect(redirect).not.toHaveBeenCalled()
    expect(screen.getByRole('heading', { level: 1 })).toBeInTheDocument()
  })
})

describe('landing page — nav', () => {
  it('shows the Cairn wordmark', async () => {
    const { container } = await renderLanding()
    expect(within(container.querySelector('nav')!).getByText('Cairn')).toBeInTheDocument()
  })

  it('links to every section of the page', async () => {
    const { container } = await renderLanding()
    const nav = within(container.querySelector('nav')!)
    for (const [label, href] of [
      ['Product tour', '#tour'],
      ['Features', '#features'],
      ['How it works', '#how'],
      ['Monthly plan', '#plan'],
    ]) {
      expect(nav.getByRole('link', { name: label })).toHaveAttribute('href', href)
    }
  })

  it('points Log in and Get started at the auth routes', async () => {
    const { container } = await renderLanding()
    const nav = within(container.querySelector('nav')!)
    expect(nav.getByRole('link', { name: 'Log in' })).toHaveAttribute('href', '/auth/login')
    expect(nav.getByRole('link', { name: 'Get started' })).toHaveAttribute('href', '/auth/signup')
  })

  it('offers the EN/VI toggle with the page locale marked active', async () => {
    const { container } = await renderLanding('en')
    const nav = within(container.querySelector('nav')!)
    const en = nav.getByRole('button', { name: 'en' })
    const vi = nav.getByRole('button', { name: 'vi' })
    // Active = full-white label; the inactive one is dimmed.
    expect(en).toHaveStyle({ color: '#fff' })
    expect(vi).not.toHaveStyle({ color: '#fff' })
  })
})

describe('landing page — hero', () => {
  it('leads with the headline, in the page locale', async () => {
    await renderLanding('en')
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('perfectly tracked')
  })

  it('serves the Vietnamese headline on the Vietnamese page', async () => {
    await renderLanding('vi')
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('mục tiêu')
  })

  it('sends the primary CTA to signup and the secondary one to the How-it-works section', async () => {
    const { container } = await renderLanding()
    const ctas = within(container.querySelector('.lp-hero-ctas')!)
    expect(ctas.getByRole('link', { name: 'Get started free' })).toHaveAttribute('href', '/auth/signup')
    expect(ctas.getByRole('link', { name: /how it works/i })).toHaveAttribute('href', '#how')
  })
})

describe('landing page — content sections', () => {
  it('shows six feature cards, including goal-based tracking', async () => {
    const { container } = await renderLanding()
    const features = container.querySelector<HTMLElement>('#features')!
    expect(features.querySelectorAll('h3')).toHaveLength(6)
    expect(within(features).getByRole('heading', { name: 'Goal-based tracking' })).toBeInTheDocument()
  })

  it('shows three numbered steps under How it works', async () => {
    const { container } = await renderLanding()
    const how = container.querySelector<HTMLElement>('#how')!
    expect(how.querySelectorAll('h3')).toHaveLength(3)
    for (const num of ['01', '02', '03']) {
      expect(within(how).getByText(num)).toBeInTheDocument()
    }
  })

  it('renders the monthly-plan spotlight', async () => {
    const { container } = await renderLanding()
    expect(container.querySelector('#plan')).toBeInTheDocument()
  })
})

describe('landing page — closing CTA', () => {
  it('repeats the signup CTA', async () => {
    const { container } = await renderLanding()
    const cta = within(container.querySelector('.lp-cta')!)
    expect(cta.getByRole('heading', { name: /financial future/i })).toBeInTheDocument()
    expect(cta.getByRole('link', { name: 'Get started free' })).toHaveAttribute('href', '/auth/signup')
  })

  it('sends "See the product tour" to the tour, not to the login form', async () => {
    // This button used to be a link to /auth/login while promising a demo: a
    // visitor who clicked to look before committing landed on a sign-in page.
    const { container } = await renderLanding()
    const cta = within(container.querySelector('.lp-cta')!)
    expect(cta.getByRole('link', { name: 'See the product tour' })).toHaveAttribute('href', '#tour')
  })
})
