// The maturity-resolve sheet's copy (#602).
//
// 121 lines of inline `const t = isVi ? {…} : {…}` sat in the middle of
// MaturityResolveBody, between its state and its markup. Same two objects,
// same keys — they just no longer pad out the component.
//
// The app hasn't moved this flow onto next-intl message catalogues; when it
// does, this is the one file that changes.
/**
 * @param matured Whether the deposit is already past its maturity date — the
 *   only thing the copy varies on beyond the locale (the "why are you seeing
 *   this" line reads differently before and after).
 */
export function maturityResolveStrings(isVi: boolean, matured: boolean) {
  return isVi ? {
    summarySuffix: 'năm', perYr: 'năm', mo: 'tháng',
    why: matured
      ? 'Sổ đã đáo hạn. Nếu không xử lý, ngân hàng thường tự tái tục theo kỳ hạn cũ. Hãy ghi nhận quyết định của bạn.'
      : 'Sổ sắp đáo hạn. Chọn cách xử lý cho kỳ tiếp theo.',
    prompt: 'Bạn muốn làm gì?',
    newAmount: 'Số tiền kỳ mới', interestReceived: 'Lãi thực nhận',
    interestPaidOut: 'Lãi thực nhận (rút ra)',
    interestSavedHint: 'Số lãi này được lưu vĩnh viễn vào lịch sử tái tục.',
    newTerm: 'Kỳ hạn mới', newRate: 'Lãi suất kỳ mới',
    newCycle: 'Kỳ mới', newMaturityLabel: 'Ngày đáo hạn mới',
    maturityHint: 'Tự tính theo kỳ hạn, tính từ ngày đáo hạn cũ. Sửa nếu ngân hàng chốt ngày khác.',
    resetDate: 'Đặt lại', maturityTooEarly: 'Ngày đáo hạn mới phải sau ngày đáo hạn cũ.',
    interestIn: 'Lãi nhập gốc', interestOut: 'Lãi rút ra',
    totalPayout: 'Tổng nhận về',
    cancel: 'Hủy', confirmRenew: 'Xác nhận tái tục', confirmWithdraw: 'Đánh dấu chờ rút',
    renewed: 'Đã tái tục', renewedSub: (p: string, d: string) => `Kỳ mới ${p} · đáo hạn ${d}`,
    combineLabel: 'Tất toán & gửi lại (gộp định kỳ)',
    combineSubPick: 'Chọn khoản định kỳ để gộp',
    combineSub: (amt: string) => `Cộng ${amt} định kỳ tháng này rồi gửi lại`,
    whichRecurring: 'Gộp kèm khoản định kỳ nào?',
    pickHint: 'Chọn một khoản để gộp, hoặc bỏ trống để chỉ tái tục gốc + lãi.',
    toAccount: 'Về tài khoản thường', principalOut: 'Gốc tất toán',
    recurringThisMonth: 'Gửi định kỳ tháng này',
    redepositAmount: 'Số tiền gửi lại',
    redepositHint: (amt: string) => `Gợi ý ${amt} (gốc + lãi + định kỳ) — sửa nếu thực tế khác.`,
    markDeposited: (amt: string) => `Đánh dấu đã gửi định kỳ tháng này (${amt})`,
    confirmCombine: 'Lưu sổ mới',
    mergeSub: 'Gộp sổ tiết kiệm khác vào lần gửi lại',
    mergeTitle: 'Gộp sổ khác',
    mergeTitleMulti: 'Gộp nhiều nguồn',
    mergeHint: 'Chọn các sổ để tất toán sớm và gộp vào lần gửi lại này.',
    mergeReceivedLabel: 'Thực nhận',
    mergeTotalLabel: 'Tổng gộp thêm',
    mergePenalty: 'Tất toán trước hạn có thể bị phạt lãi — nhập số tiền thực nhận, không phải giá trị hiện tại.',
    destBankLabel: 'Ngân hàng đích',
    destBankNone: 'Không chọn',
    destBankHint: 'Đổi nếu bạn gửi lại ở ngân hàng khác.',
    provenance: (n: number, m: number) => `Gộp từ ${n} nguồn · ${m} ngân hàng`,
    mergedSourcesLabel: 'Đã gộp',
    windowLabel: (n: number) => `Cửa sổ đáo hạn: ${n} ngày`,
    windowHint: 'Nới cửa sổ để gộp thêm sổ — chờ lâu hơn = thiệt lãi.',
    mergeEarly: 'Gộp sớm?',
    reasonOutOfWindow: (n: number) => `Đáo hạn cách ${n} ngày — phá kỳ mất lãi`,
    reasonCurrency: 'Khác loại tiền',
    reasonPledged: 'Đang thế chấp — bị phong toả',
    // The anchor, not the source: the deposit the money would go INTO is frozen,
    // so nothing can be folded in until the pledge is released (#635).
    reasonPledgedAnchor: 'Sổ này đang thế chấp — không nhận thêm tiền',
    reasonGoal: 'Khác mục tiêu',
    reasonBlocked: 'Chưa đủ điều kiện',
    holdNudge: (anchor: string, date: string) => `«${anchor}» đáo hạn ${date} cùng mục tiêu — để dành gộp thay vì rút?`,
    holdForkPrompt: 'Tất toán sổ này thế nào?',
    holdCardTitle: 'Để dành gộp',
    holdCardSub: (anchor: string) => `Giữ tiền chờ gộp vào «${anchor}» — không rời mục tiêu`,
    cashCardTitle: 'Rút ra ví',
    cashCardSub: 'Tiền rời khỏi mục tiêu như rút thường',
    holdReceivedLabel: 'Số tiền thực nhận',
    holdConfirm: 'Xác nhận để dành',
    holdDone: 'Đã để dành gộp',
    holdDoneSub: (anchor: string) => `Đang chờ gộp vào «${anchor}»`,
    heldSectionTitle: 'Ví chờ gộp',
    heldSectionHint: 'Các sổ đã tất toán để dành — gộp vào lần gửi lại này.',
    heldUnholdHint: 'Bỏ chọn để giữ lại trong ví chờ gộp.',
  } : {
    summarySuffix: 'yr', perYr: 'yr', mo: 'mo',
    why: matured
      ? 'This deposit has matured. Banks usually auto-renew at the same term — record what you decided.'
      : 'This deposit is about to mature. Choose how to handle the next cycle.',
    prompt: 'What do you want to do?',
    newAmount: 'New amount', interestReceived: 'Interest received',
    interestPaidOut: 'Interest received (paid out)',
    interestSavedHint: 'This interest is saved permanently to the renewal history.',
    newTerm: 'New term', newRate: 'New interest rate',
    newCycle: 'New cycle', newMaturityLabel: 'New maturity',
    maturityHint: 'Auto-calculated from the term, starting at the old maturity date. Edit if your bank set a different date.',
    resetDate: 'Reset', maturityTooEarly: 'New maturity must be after the old maturity date.',
    interestIn: 'Interest added', interestOut: 'Interest out',
    totalPayout: 'Total payout',
    cancel: 'Cancel', confirmRenew: 'Confirm renewal', confirmWithdraw: 'Mark for withdrawal',
    renewed: 'Deposit renewed', renewedSub: (p: string, d: string) => `New term ${p} · matures ${d}`,
    combineLabel: 'Settle & re-deposit (merge recurring)',
    combineSubPick: 'Pick a recurring to merge',
    combineSub: (amt: string) => `Add ${amt} recurring, then re-deposit`,
    whichRecurring: 'Which recurring to merge?',
    pickHint: 'Pick one to merge, or leave none to renew principal + interest only.',
    toAccount: 'To your account', principalOut: 'Principal out',
    recurringThisMonth: 'Recurring this month',
    redepositAmount: 'Re-deposit amount',
    redepositHint: (amt: string) => `Suggested ${amt} (principal + interest + recurring) — edit if reality differs.`,
    markDeposited: (amt: string) => `Mark this month's recurring as deposited (${amt})`,
    confirmCombine: 'Save new deposit',
    mergeSub: 'Fold other deposits into the re-deposit',
    mergeTitle: 'Merge other deposits',
    mergeTitleMulti: 'Merge multiple sources',
    mergeHint: 'Pick deposits to settle early and fold into this re-deposit.',
    mergeReceivedLabel: 'Received',
    mergeTotalLabel: 'Total merged in',
    mergePenalty: 'Early settlement may forfeit interest — enter the cash received, not the current value.',
    destBankLabel: 'Destination bank',
    destBankNone: 'No bank',
    destBankHint: 'Change it if you re-deposit at another bank.',
    provenance: (n: number, m: number) => `Combined from ${n} sources · ${m} banks`,
    mergedSourcesLabel: 'Merged in',
    windowLabel: (n: number) => `Maturity window: ${n} days`,
    windowHint: 'Widen the window to fold in more deposits — waiting longer forfeits interest.',
    mergeEarly: 'Merge early?',
    reasonOutOfWindow: (n: number) => `Matures ${n}d apart — early settlement`,
    reasonCurrency: 'Different currency',
    reasonPledged: 'Pledged as collateral',
    reasonPledgedAnchor: 'This deposit is pledged — it cannot take more money',
    reasonGoal: 'Different goal',
    reasonBlocked: 'Not eligible yet',
    holdNudge: (anchor: string, date: string) => `“${anchor}” matures ${date} in the same goal — hold for merge instead of withdrawing?`,
    holdForkPrompt: 'How do you want to settle this?',
    holdCardTitle: 'Hold for merge',
    holdCardSub: (anchor: string) => `Keep the cash for merging into “${anchor}” — stays in the goal`,
    cashCardTitle: 'Withdraw to wallet',
    cashCardSub: 'Money leaves the goal, like a normal withdrawal',
    holdReceivedLabel: 'Cash received',
    holdConfirm: 'Confirm hold',
    holdDone: 'Held for merge',
    holdDoneSub: (anchor: string) => `Waiting to merge into “${anchor}”`,
    heldSectionTitle: 'Merge holding pool',
    heldSectionHint: 'Deposits already settled and parked — fold them into this re-deposit.',
    heldUnholdHint: 'Deselect to leave it in the pool.',
  }
}
