import type { Metadata } from 'next'

// Everything a crawler or a link scraper sees, in one place.
//
// The signed-in screens have always localized their titles (`generateMetadata` in
// app/(app)/*/page.tsx reads nav.*), but those pages redirect to /auth/login for anyone
// without a session — so the only page Google, Zalo, Messenger or Facebook can actually
// read was the landing page, and it was serving a bare `<title>Cairn</title>` plus an
// English description on a Vietnamese-by-default site, with no Open Graph tags at all.

/**
 * Canonical origin, always production — never the deployment currently serving the request.
 *
 * `VERCEL_PROJECT_PRODUCTION_URL` is the production domain even when the code is running on
 * a preview deployment, which is exactly what canonical URLs and OG images want: a preview
 * must not advertise itself as the real thing, or crawlers index the preview host.
 */
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ??
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : 'https://cairn-money.vercel.app')

/** The social card. Generated by scripts/generate-og-image.mjs; 1200×630 is the size
 *  Facebook, Zalo and X all lay out against. */
const OG_IMAGE = '/og-image.png'
const OG_IMAGE_W = 1200
const OG_IMAGE_H = 630

const LOCALES = ['vi', 'en'] as const
export type Locale = (typeof LOCALES)[number]

/** Open Graph wants a full locale tag, not a bare language code. */
const OG_LOCALE: Record<Locale, string> = { vi: 'vi_VN', en: 'en_US' }

/** BCP 47, which is what schema.org's inLanguage expects (OG uses underscores instead). */
const BCP47: Record<Locale, string> = { vi: 'vi-VN', en: 'en-US' }

export function normalizeLocale(locale: string): Locale {
  return (LOCALES as readonly string[]).includes(locale) ? (locale as Locale) : 'vi'
}

/**
 * schema.org JSON-LD for the landing page.
 *
 * Metadata tags say how to *display* the page; this says what it *is* — a free finance
 * app, in this language, on these platforms — which is what earns a rich result rather
 * than a plain blue link.
 *
 * `price: '0'` is deliberate and load-bearing: "is it free?" is the question a visitor has
 * before signing up, and it is the one thing a search result can answer for them.
 */
export function buildStructuredData(locale: string, t: (key: string) => string) {
  const loc = normalizeLocale(locale)
  return {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: 'Cairn',
    url: `${SITE_URL}/`,
    description: t('description'),
    applicationCategory: 'FinanceApplication',
    operatingSystem: 'Web, iOS, Android',
    inLanguage: BCP47[loc],
    image: `${SITE_URL}${OG_IMAGE}`,
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'VND',
    },
  }
}

/**
 * Builds the site-wide metadata for a locale.
 *
 * Kept a pure function of (locale, translate) so it can be unit-tested directly — asserting
 * the object is cheaper and catches more than booting Next and scraping its own <head>.
 */
export function buildSiteMetadata(locale: string, t: (key: string) => string): Metadata {
  const loc = normalizeLocale(locale)
  const title = t('title')
  const description = t('description')

  return {
    metadataBase: new URL(SITE_URL),
    // `default` rather than a bare string so the signed-in screens keep composing their
    // own titles through the existing '%s | Cairn' template.
    title: { template: '%s | Cairn', default: title },
    description,
    applicationName: 'Cairn',
    alternates: {
      canonical: '/',
      languages: { vi: '/', en: '/' },
    },
    openGraph: {
      type: 'website',
      siteName: 'Cairn',
      locale: OG_LOCALE[loc],
      url: '/',
      title,
      description,
      images: [{ url: `${SITE_URL}${OG_IMAGE}`, width: OG_IMAGE_W, height: OG_IMAGE_H, alt: t('ogAlt') }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [`${SITE_URL}${OG_IMAGE}`],
    },
    manifest: '/manifest.webmanifest',
    appleWebApp: { capable: true, statusBarStyle: 'default', title: 'Cairn' },
    icons: {
      icon: [
        { url: '/favicon-32.png?v=3', sizes: '32x32', type: 'image/png' },
        { url: '/icon-192.png?v=3', sizes: '192x192', type: 'image/png' },
      ],
      apple: [{ url: '/apple-touch-icon.png?v=3', sizes: '180x180', type: 'image/png' }],
    },
  }
}
