import { readFileSync } from 'fs'
import path from 'path'
import { describe, it, expect } from 'vitest'

// Guard for #596: CI used to gate merges on typecheck + unit tests alone, so a
// broken migration, a lint error, a build failure, or a dead smoke path could
// merge — and the production migration job shipped on that same thin signal.
// These assertions lock in the shape of the gate: five independently-reported
// jobs, and a production deploy that waits on all of them.
//
// Read the workflow as text rather than parsing YAML — the repo has no YAML
// parser dependency, and the questions here ("is there a job called X", "what
// does migrate need") are answerable structurally without one.
const root = path.resolve(__dirname, '..')
const ci = readFileSync(path.join(root, '.github/workflows/ci.yml'), 'utf8')

/** Top-level job ids: keys indented exactly two spaces under `jobs:`. */
function jobIds(workflow: string): string[] {
  const jobs = workflow.slice(workflow.indexOf('\njobs:'))
  return [...jobs.matchAll(/^ {2}([a-z0-9][a-z0-9-]*):$/gm)].map((m) => m[1])
}

/** The `needs:` entries of a job, whether written inline or as a list. */
function needsOf(workflow: string, job: string): string[] {
  const start = workflow.indexOf(`\n  ${job}:\n`)
  expect(start, `job "${job}" not found`).toBeGreaterThan(-1)
  const block = workflow.slice(start + 1)
  const inline = block.match(/^ {4}needs:\s*\[([^\]]*)\]/m)
  if (inline) return inline[1].split(',').map((s) => s.trim()).filter(Boolean)
  const single = block.match(/^ {4}needs:\s*([a-z0-9-]+)\s*$/m)
  return single ? [single[1]] : []
}

describe('CI quality gates (#596)', () => {
  it('reports unit, lint, build, DB and smoke-E2E status as independent jobs', () => {
    // One job per gate: a red X on the PR names the thing that broke instead of
    // collapsing every check into "Unit Tests".
    expect(jobIds(ci)).toEqual(expect.arrayContaining(['test', 'lint', 'build', 'db', 'e2e-smoke']))
  })

  it('runs lint and a production build on every PR', () => {
    expect(ci).toMatch(/npm run lint/)
    expect(ci).toMatch(/npm run build/)
  })

  it('exercises the SQL suite against a Supabase stack started from scratch', () => {
    // `supabase start` on a fresh runner replays every migration onto an empty
    // database, so this is also the "migrations apply cleanly" gate.
    expect(ci).toMatch(/supabase start/)
    expect(ci).toMatch(/npm run test:db/)
  })

  it('enforces unit-test coverage rather than running bare vitest', () => {
    expect(ci).toMatch(/npm run test:coverage/)
  })

  it('gates the production migration push on every check, not just unit tests', () => {
    // The migrate job writes to the production schema. Anything that can fail
    // must be able to stop it.
    expect(needsOf(ci, 'migrate')).toEqual(
      expect.arrayContaining(['test', 'lint', 'build', 'db', 'e2e-smoke']),
    )
    expect(ci).toMatch(/supabase db push/)
  })
})

describe('coverage configuration (#596)', () => {
  const cfg = readFileSync(path.join(root, 'vitest.config.ts'), 'utf8')

  it('measures every application/server source file, not only imported ones', () => {
    // The include patterns are what pull untested files into the report as 0%
    // instead of leaving them out and overstating the global percentage.
    expect(cfg).toMatch(/include:\s*\[[^\]]*app\/\*\*/)
    expect(cfg).toMatch(/include:\s*\[[^\]]*lib\/\*\*/)
    expect(cfg).toMatch(/include:\s*\[[^\]]*components\/\*\*/)
  })

  it('sets thresholds for the critical money routes, not just a global number', () => {
    expect(cfg).toMatch(/thresholds:/)
    expect(cfg).toMatch(/app\/api\/v1\/investment-transactions\/route\.ts/)
    expect(cfg).toMatch(/app\/api\/v1\/investment-transactions\/\[id\]\/route\.ts/)
    expect(cfg).toMatch(/app\/api\/v1\/dashboard\/overview\/route\.ts/)
  })
})

// Guard for #685: a clean `npm ci` on main failed with
// "Missing: @swc/helpers@0.5.23 from lock file". The lockfile is generated by
// npm 11, which treats `@swc/core`'s optional peer on @swc/helpers as skippable;
// npm 10 — the version Node 20 *and* Node 22 still bundle — wants that peer as a
// nested entry and refuses the lock without it. Nothing caught it because every
// job ran `npm install`, which silently repairs the graph from the registry at
// run time. These assertions keep the install reproducible: one declared
// toolchain, and `npm ci` everywhere the app's dependencies are installed.
describe('reproducible installs (#685)', () => {
  const e2e = readFileSync(path.join(root, '.github/workflows/e2e.yml'), 'utf8')
  const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
  const nvmrc = readFileSync(path.join(root, '.nvmrc'), 'utf8').trim()
  const workflows = { 'ci.yml': ci, 'e2e.yml': e2e }

  it.each(Object.keys(workflows))('installs from the lockfile in %s', (name) => {
    const workflow = workflows[name as keyof typeof workflows]
    // `npm install` resolves against the registry and rewrites the lock; `npm ci`
    // installs exactly what is committed and fails loudly when it can't.
    expect(workflow).toMatch(/run: npm ci\b/)
    expect(workflow).not.toMatch(/run: npm install\b/)
  })

  it.each(Object.keys(workflows))('takes the Node version from .nvmrc in %s', (name) => {
    const workflow = workflows[name as keyof typeof workflows]
    // One declared version, read by both CI and `nvm use` locally — a hardcoded
    // `node-version:` is how the runner drifted away from the dev toolchain.
    expect(workflow).toMatch(/node-version-file: \.nvmrc/)
    expect(workflow).not.toMatch(/node-version: \d/)
  })

  it.each(Object.keys(workflows))('pins an npm that accepts this lockfile in %s', (name) => {
    const workflow = workflows[name as keyof typeof workflows]
    // Node 22 still bundles npm 10, so setup-node alone is not enough: every job
    // that installs has to upgrade npm before it runs `npm ci`.
    const pins = [...workflow.matchAll(/npm i -g npm@(\d+)\.\d+\.\d+/g)].map((m) => m[1])
    const installs = [...workflow.matchAll(/run: npm ci\b/g)].length
    expect(pins.length).toBe(installs)
    expect(pins.every((major) => major === '11')).toBe(true)
  })

  it('declares the supported Node and npm versions in package.json', () => {
    expect(pkg.engines?.node).toBeDefined()
    expect(pkg.engines?.npm).toBeDefined()
    expect(pkg.engines.npm).toContain('11')
  })

  it('claims only the Node 22 minors the dependency graph actually supports', () => {
    // A bare major ("22.x", ".nvmrc" of "22") over-promises: `jsdom@29` — a direct
    // devDependency — needs ^22.13.0, so Node 22.0–22.12 warns on install and fails
    // outright under engine-strict while the root package claims to support it.
    // Derive the floor from the lock so a future dependency bump moves this test,
    // not a hand-maintained number.
    const floor = highestNode22Floor()
    expect(atLeast(parse(nvmrc), floor)).toBe(true)
    expect(atLeast(nodeRangeFloor(pkg.engines.node), floor)).toBe(true)
  })

  type Version = [number, number, number]

  /** "22.18.0" / "v22.18.0" → [22, 18, 0]; a missing minor or patch reads as 0. */
  function parse(version: string): Version {
    const [major = 0, minor = 0, patch = 0] = version
      .trim()
      .replace(/^v/, '')
      .split('.')
      .map(Number)
    return [major, minor, patch]
  }

  function atLeast(a: Version, b: Version): boolean {
    return a[0] !== b[0] ? a[0] > b[0] : a[1] !== b[1] ? a[1] > b[1] : a[2] >= b[2]
  }

  /**
   * The lowest Node 22 this range admits, from its `^22.x` / `>=22.x` term —
   * null when the range pins no 22-specific bound (`>=16.0.0` admits every 22).
   */
  function node22Floor(range: string): Version | null {
    const term = range.match(/(?:\^|>=)\s*22(?:\.(\d+))?(?:\.(\d+))?/)
    return term ? [22, Number(term[1] ?? 0), Number(term[2] ?? 0)] : null
  }

  /** Same, for a version we declare ourselves — where a missing bound is a bug. */
  function nodeRangeFloor(range: string): Version {
    const floor = node22Floor(range)
    expect(floor, `"${range}" names no Node 22 lower bound`).not.toBeNull()
    return floor!
  }

  /** The strictest Node 22 floor any package in the lock asks for. */
  function highestNode22Floor(): Version {
    const lock = JSON.parse(readFileSync(path.join(root, 'package-lock.json'), 'utf8'))
    let floor: Version = [22, 0, 0]
    for (const [name, entry] of Object.entries<{ engines?: { node?: string } }>(lock.packages)) {
      const asked = name === '' ? null : node22Floor(entry.engines?.node ?? '')
      if (asked && atLeast(asked, floor)) floor = asked
    }
    return floor
  }
})

// Guard for #696: `Install Playwright browsers` stalled on two consecutive `main`
// runs, each time eating the E2E job's whole 30-minute budget — and because
// `Apply DB migrations (production)` needs e2e-smoke, a hung download SKIPPED the
// migration push. On #687 that left Vercel serving code that called a function
// the production database did not have yet. ci.yml already names this class of
// failure as "the one failure in this pipeline that does not heal on its own";
// a browser download reaching the same outcome by another road is worth pinning.
describe('Playwright browser install (#696)', () => {
  const e2e = readFileSync(path.join(root, '.github/workflows/e2e.yml'), 'utf8')

  /** The `- name: …` step block that contains `needle`, up to the next step. */
  function stepContaining(workflow: string, needle: string): string {
    const at = workflow.indexOf(needle)
    expect(at, `no step runs "${needle}"`).toBeGreaterThan(-1)
    const start = workflow.lastIndexOf('\n      - ', at)
    const end = workflow.indexOf('\n      - ', at)
    return workflow.slice(start, end === -1 ? undefined : end)
  }

  it('caches the browsers instead of downloading them every run', () => {
    expect(e2e).toMatch(/actions\/cache/)
    // The store Playwright actually reads. A cache of anything else is a cache
    // that still downloads.
    expect(e2e).toMatch(/~\/\.cache\/ms-playwright/)
  })

  it('keys the cache by the Playwright version, not by a fixed string', () => {
    // A constant key serves last month's browsers to this month's Playwright,
    // which fails at runtime rather than at install time — the worst place for it.
    expect(e2e).toMatch(/key:.*playwright.*\$\{\{\s*steps\./i)
  })

  it('still installs the system packages when the cache hits', () => {
    // ~/.cache/ms-playwright holds the browsers, not the apt libraries they link
    // against. Restoring it and skipping `install-deps` gives a browser that
    // cannot start.
    expect(e2e).toMatch(/playwright install-deps/)
  })

  it('bounds the install step itself, well under the job budget', () => {
    const step = stepContaining(e2e, 'playwright install')
    const stepTimeout = step.match(/timeout-minutes:\s*(\d+)/)
    expect(stepTimeout, 'the install step needs its own timeout-minutes').not.toBeNull()

    const jobTimeout = e2e.match(/^ {4}timeout-minutes:\s*(\d+)/m)
    expect(jobTimeout).not.toBeNull()
    // The point is to fail the step and leave the job room, not to hang until the
    // job dies and takes the migration push with it.
    expect(Number(stepTimeout![1])).toBeLessThan(Number(jobTimeout![1]) / 2)
  })

  it('retries a failed install once before giving up', () => {
    const step = stepContaining(e2e, 'playwright install')
    // One bad fetch should not need a human to re-run the pipeline.
    expect(step).toMatch(/for attempt|retry|\|\|.*playwright install/i)
  })
})
